Enable PepDB module test
LabKey/pepdb pull request #13
Opened 2021-08-13 21:47 UTC by labkey-tchad

#### Rationale
Not sure why this is disabled or how much work it would be to get it working.

#### Related Pull Requests
* https://github.com/LabKey/testAutomation/pull/838

#### Changes
* Remove `Disabled` category from `PepDBModuleTest`

2021-08-17 21:28 UTC, labkey-adam requested changes
Add targets to links to maintain current behavior. Or maybe you removed them on intentionally?

2021-08-17 21:28 UTC, labkey-adam commented on src/org/scharp/atlas/pepdb/PepDBBaseController.java
> +                                    .addParameter(PepDBSchema.COLUMN_PEPTIDE_ID, peptideId))
`.target("_self")`?

2021-08-17 21:28 UTC, labkey-adam commented on src/org/scharp/atlas/pepdb/PepDBBaseController.java
> +                                    .addParameter(PepDBSchema.COLUMN_PEPTIDE_POOL_ID, peptidePoolId))
`.target("_self")`?

2021-08-17 21:28 UTC, labkey-adam commented on src/org/scharp/atlas/pepdb/PepDBBaseController.java
> +                                        .addParameter(PepDBSchema.COLUMN_PEPTIDE_POOL_ID, parentPoolId))
`.target("_self")`?

2021-08-18 00:45 UTC, labkey-jeckels commented
Since Adam's already taken a look I won't review separately unless there's a good reason for me to

2021-08-18 00:48 UTC, labkey-adam approved these changes

2021-08-18 00:49 UTC, labkey-adam commented
Agreed, no need for @labkey-jeckels to review

2021-08-18 17:21 UTC, merged